-- Query 1
SELECT a.TRANSACTION_ID,to_char(a.AMOUNT,'$999.00') "Amount Due",d.FIRST_NAME,d.LAST_NAME,d.PHONE,
   d.EMAIL,d.APT_NO,d.STREET,d.CITY,d.STATENAME,d.ZIP,a.STATUS,a.STATUS_DATE,c.VEHICLE_ID
    FROM T7_BILL_DETAILS a
    JOIN (SELECT  TRANSACTION_ID,MAX(STATUS_DATE) "STATUS_DATE" FROM T7_BILL_DETAILS   
    WHERE TRANSACTION_ID NOT IN(SELECT TRANSACTION_ID FROM T7_BILL_DETAILS WHERE STATUS = 'Payment Done') 
    GROUP BY TRANSACTION_ID) b 
    ON a.TRANSACTION_ID = b.TRANSACTION_ID AND a.STATUS_DATE = b.STATUS_DATE
    JOIN T7_PARKING_DETAILS c ON c.TRANSACTION_ID = a.TRANSACTION_ID 
    JOIN T7_USER_DETAILS d ON c.VEHICLE_ID = d.VEHICLE_ID;

-- Query 2
SELECT b.LOT_ID,to_char(SUM(a.AMOUNT),'$999.00') "Earnings"
    FROM T7_BILL_DETAILS a 
    JOIN T7_PARKING_DETAILS b ON b.TRANSACTION_ID = a.TRANSACTION_ID 
    WHERE a.STATUS='Payment Done'
    GROUP BY b.LOT_ID;
    
-- Query 3
SELECT a.LOT_ID,a.SPACES - NVL(b."Occupied",0) "Available Spaces" FROM T7_LOT_DETAILS a 
    LEFT OUTER JOIN (SELECT LOT_ID,COUNT(*) "Occupied" FROM T7_PARKING_DETAILS 
    WHERE OUT_TIME is NULL GROUP BY LOT_ID) b
    ON a.LOT_ID = b.LOT_ID
    WHERE a.LOT_ID = &LOT_ID;
